-- Insert SQL Rules Here 
--==========================================================================================================================
-- Diplomacy_Responses
--==========================================================================================================================
INSERT INTO Diplomacy_Responses
(LeaderType, 				ResponseType, 											Response, 																	Bias)
VALUES		('LEADER_CLSEATTLE', 	'RESPONSE_MINOR_CIV_COMPETITION', 			'TXT_KEY_LEADER_CLSEATTLE_MINOR_CIV_COMPETITION%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_CLSEATTLE_FIRSTGREETING%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_CLSEATTLE_DEFEATED%', 									2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_CLSEATTLE_REPEAT_TOO_MUCH%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_CLSEATTLE_REPEAT_TRADE_TOO_MUCH%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_CLSEATTLE_REPEAT_TOO_MUCH%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HELLO%', 					2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_CLSEATTLE_GREETING_POLITE_HELLO%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_AT_WAR%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_CLSEATTLE_GREETING_HUMAN_AT_WAR%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_CLSEATTLE_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 		2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_CLSEATTLE_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 	2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_CLSEATTLE_GREETING_AGGRESSIVE_PLOT_BUYING%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 		2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_CLSEATTLE_GREETING_AGGRESSIVE_EXPANSION%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_CLSEATTLE_GREETING_FRIENDLY_STRONG_MILITARY%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_CLSEATTLE_GREETING_FRIENDLY_STRONG_ECONOMY%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 		2),
('LEADER_CLSEATTLE', 	'RESPONSE_TOO_SOON_FOR_DOF', 							'TXT_KEY_LEADER_CLSEATTLE_TOO_SOON_FOR_DOF%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_CLSEATTLE_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_CLSEATTLE_DENOUNCE%', 									2),
('LEADER_CLSEATTLE', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_CLSEATTLE_DENOUNCE%', 									2),
('LEADER_CLSEATTLE', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_CLSEATTLE_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DOFED_FRIEND', 							'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOFED_FRIEND%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DOFED_ENEMY', 							'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOFED_ENEMY%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DENOUNCED_ENEMY', 						'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCED_ENEMY%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DENOUNCED_FRIEND', 						'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCED_FRIEND%', 					2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DOF_SO_AI_DOF', 						'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOF_SO_AI_DOF%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE', 				'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCE_SO_AI_DENOUNCE%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE', 					'TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOF_SO_AI_DENOUNCE%', 					2),
('LEADER_CLSEATTLE', 	'RESPONSE_COOP_WAR_REQUEST', 							'TXT_KEY_LEADER_CLSEATTLE_COOP_WAR_REQUEST%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_COOP_WAR_TIME', 								'TXT_KEY_LEADER_CLSEATTLE_COOP_WAR_TIME%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_WORK_WITH_US', 								'TXT_KEY_LEADER_CLSEATTLE_DEC_FRIENDSHIP%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_PLOT_BUYING_WARNING', 						'TXT_KEY_LEADER_CLSEATTLE_PLOT_BUYING_WARNING%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 				'TXT_KEY_LEADER_CLSEATTLE_PLOT_BUYING_SERIOUS_WARNING%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 					'TXT_KEY_LEADER_CLSEATTLE_EXPANSION_SERIOUS_WARNING%', 					2),
('LEADER_CLSEATTLE', 	'RESPONSE_EXPANSION_WARNING', 							'TXT_KEY_LEADER_CLSEATTLE_EXPANSION_WARNING%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 				'TXT_KEY_LEADER_CLSEATTLE_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_RETURNED_CIVILIAN', 							'TXT_KEY_LEADER_CLSEATTLE_RETURNED_CIVILIAN%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_DECLARATION_PROTECT_CITY_STATE', 				'TXT_KEY_LEADER_CLSEATTLE_DECLARATION_PROTECT_CITY_STATE%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_BULLIED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_CLSEATTLE_BULLIED_PROTECTED_CITY_STATE%', 				2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_PROTECTED_CITY_STATEE%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_DECLARATION_ABANDON_CITY_STATE', 				'TXT_KEY_LEADER_CLSEATTLE_DECLARATION_ABANDON_CITY_STATE%', 			2),
('LEADER_CLSEATTLE', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_CLSEATTLE_DONT_SETTLE_YES%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_CLSEATTLE_DONT_SETTLE_NO%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_LUXURY_TRADE', 								'TXT_KEY_LEADER_CLSEATTLE_LUXURY_TRADE%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 						'TXT_KEY_LEADER_CLSEATTLE_OPEN_BORDERS_EXCHANGE%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_REQUEST', 									'TXT_KEY_LEADER_CLSEATTLE_RESPONSE_REQUEST%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_HOSTILE%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_HOSTILE%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_HOSTILE%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_EXCITED%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_EXCITED%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_EXCITED%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_SAD%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_CLSEATTLE_ATTACKED_BETRAYED%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_CLSEATTLE_DOW_GENERIC%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_CLSEATTLE_DOW_LAND%', 									2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_CLSEATTLE_DOW_WORLD_CONQUEST%', 						2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_CLSEATTLE_DOW_OPPORTUNITY%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_CLSEATTLE_DOW_DESPERATE%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_DOW_REGRET', 									'TXT_KEY_LEADER_CLSEATTLE_DOW_REGRET%', 								2),
('LEADER_CLSEATTLE', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_CLSEATTLE_TOO_SOON_NO_PEACE%', 							2),
('LEADER_CLSEATTLE', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',	'TXT_KEY_LEADER_CLSEATTLE_GOOD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',				'TXT_KEY_LEADER_CLSEATTLE_GOOD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',				'TXT_KEY_LEADER_CLSEATTLE_GOOD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_WE_ATTACKED_MINOR_BAD',						'TXT_KEY_LEADER_CLSEATTLE_GOOD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD', 	'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_ATTACKED_MINOR_BAD', 					'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD', 		'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD', 		'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD', 				'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 			'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD', 				'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_WE_ATTACKED_MINOR_GOOD', 						'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD', 					'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD', 		'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD', 		'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2),
('LEADER_CLSEATTLE', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD', 				'TXT_KEY_LEADER_CLSEATTLE_BAD%', 										2);
--==========================================================================================================================
--==========================================================================================================================
INSERT INTO Language_en_US
(Tag,																	Text)
VALUES		('TXT_KEY_LEADER_CLSEATTLE_FIRSTGREETING_1',							'Greetings! I see the favor of the spirit of God on you. Come, let us share what we know of the Creator.'),
			('TXT_KEY_LEADER_CLSEATTLE_FIRSTGREETING_2',							'Welcome to the beautiful lands of the Coast Salish. Your countenance is a gift to me from the Creator.'),
			('TXT_KEY_LEADER_CLSEATTLE_DEFEATED_1',									'God has not abandoned us. One day, when you least expect it, we will return in numbers.'),
			('TXT_KEY_LEADER_CLSEATTLE_REPEAT_TOO_MUCH_1',							'Please, you weary me with your repeated demands. Do not be like the crow, whose greed for color left him with nothing but blackness.'),
			('TXT_KEY_LEADER_CLSEATTLE_REPEAT_TRADE_TOO_MUCH_1',					'Gift-giving is the way of the Coast Salish, but repeated asking shows greed, like the vulture.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HELLO_1',					'I suppose I will listen to you today. Hopefully something good will come of it.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_POLITE_HELLO_1',					'Greetings! Let us share together in the gifts of the land.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_AT_WAR_1',			'Wisdom says that a man who raids the cities of others desires to raid your villages, too. Begone.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HUMAN_AT_WAR_1',					'I wish to ease the burden of your war. But, you should put your violence behind you and enjoy the gifts of the land.'),
			('TXT_KEY_LEADER_CLSEATTLE_AGGRESSIVE_MILITARY_WARNING_1',				'Raid the villages of the wilds, if you must, but do not love war so much as to let it consume you. Turn back from the land of the Coast Salish.'),
			('TXT_KEY_LEADER_CLSEATTLE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_1',		'You seek to slay us with blade and fire, and the poisoned eyes of the greedy. Stand down, or we will rise against you.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_AGGRESSIVE_PLOT_BUYING_1',			'By what right do you take land that was not gifted to you? This is not the way of wisdom.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING_1',	'You have no heed for the property of men, or the gifts given by the Creator. Stop buying these plots, .'),
			('TXT_KEY_LEADER_CLSEATTLE_PLOT_BUYING_WARNING_1',						'By what right do you take land that was not gifted to you? This is not the way of wisdom.'),
			('TXT_KEY_LEADER_CLSEATTLE_PLOT_BUYING_SERIOUS_WARNING_1',				'Why do you take all of the land? You will be the death of us all.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_AGGRESSIVE_EXPANSION_1',			'I spoke to you before about the way you take sacred lands for your own. You did not listen to wisdom. I am saddened by your beligerence.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION_1',	'I spoke to you before about the way you take sacred lands for your own. You did not listen to wisdom. Perhaps you will listen to force, instead.'),
			('TXT_KEY_LEADER_CLSEATTLE_EXPANSION_WARNING_1',						'The land is sacred and a gift from the Creator. Do not greedily try to take all of the Creator''s gifts for youself.'),
			('TXT_KEY_LEADER_CLSEATTLE_EXPANSION_SERIOUS_WARNING_1',				'The land is sacred and a gift from the Creator. You try to take all of the Creator''s gifts for youself, and we Coast Salish will rise to defend it.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_FRIENDLY_STRONG_MILITARY_1',		'Your God must favor you indeed, for you to have such a mighty army with many men.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_FRIENDLY_STRONG_ECONOMY_1',			'You are have great wealth and are so generous. This is what makes for a great noble.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_FEW_CITIES_1',		'Perhaps if you were not so stingy, your people would give gifts to each other and therefore multiply. But you are so small in number that a single slave raid could end you.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_SMALL_ARMY_1',		'I fear that your army is too weak to hold off a slave raid. They are so small that it looks like they already have been raided and the ones that were too weak for the slavers are all that is left.'),
			('TXT_KEY_LEADER_CLSEATTLE_GREETING_HOSTILE_HUMAN_IS_WARMONGER_1',		'Begone. You wickedness stains the land before you, for you are a lover of death.'),
			('TXT_KEY_LEADER_CLSEATTLE_TOO_SOON_FOR_DOF_1',							'The Coast Salish do not know you well enough to welcome you into our homes. But, we shall invite you to our next potlatch, so we may give each other good things.'),
			('TXT_KEY_LEADER_CLSEATTLE_DENOUNCE_1',									'I have spread the stories of your wicked ways across the waters, that others may know the truth about you.'),
			('TXT_KEY_LEADER_CLSEATTLE_DENOUNCE_2',									'I have gifted the nations with the knowledge of your evil ways.'),
			('TXT_KEY_LEADER_CLSEATTLE_RESPONSE_TO_BEING_DENOUNCED_1',				'Only the basest of men scoffs in the face of wisdom. You will change your mind soon, I suspect.'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOFED_FRIEND_1',						'I see you are friends with {1_CivName}. So are we! This is excellent, for we will have more friends, more food, and more gifts at our next potlatch!'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOFED_ENEMY_1',						'I warn you about {1_CivName}. They are not to be trusted.'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCED_FRIEND_1',					'You are mistaken about {1_CivName}, who is a generous ally of the Coast Salish.'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCED_ENEMY_1',					'{1_CivName}''s evil is also apparent to the Coast Salish. We will stand together in this dark time of change.'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOF_SO_AI_DOF_1',						'I see you are friends with {1_CivName}. So are we! This is excellent, for we will have more friends, more food, and more gifts at our next potlatch!'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DOF_SO_AI_DENOUNCE_1',					'You can always tell the true make of a leader by his friends. Because you are friends with {1_CivName}, you must be wicked as well. I will tell all of the nations what measure of a leader you truly are.'),
			('TXT_KEY_LEADER_CLSEATTLE_HUMAN_DENOUNCE_SO_AI_DENOUNCE_1',			'We will stand together against {1_CivName}, weaving our words together to form a strong barrier against evil.'),
			('TXT_KEY_LEADER_CLSEATTLE_COOP_WAR_REQUEST_1',							'Will you rise with us to defeat {1_CivName}? Their wickedness demands that we act.'),
			('TXT_KEY_LEADER_CLSEATTLE_COOP_WAR_TIME_1',							'You have made a promise to war against {1_CivName}. Now it is time to rise with us. Are you ready?'),
			('TXT_KEY_LEADER_CLSEATTLE_DEC_FRIENDSHIP_1',							'Let us give the gift of friendship to one another, and to our future generations!'),
			('TXT_KEY_LEADER_CLSEATTLE_RETURNED_CIVILIAN_1',						'You of all of the leaders of men on the earth understand that acting generously to others is the way to gain the favor of the spirit of God. I honor you.'),
			('TXT_KEY_LEADER_CLSEATTLE_MINOR_CIV_COMPETITION_1',					'You are only great because of your greed. If you wish to give gifts to {1_MinorCivName:textkey}, you should also give gifts to all peoples. Otherwise, it will create jealousy in all others.'),
			('TXT_KEY_LEADER_CLSEATTLE_MINOR_CIV_COMPETITION_2',					'You seek to supplant us as {1_MinorCivName:textkey}''s friend? We will see whose gifts they respond to more!'),
			('TXT_KEY_LEADER_CLSEATTLE_DECLARATION_PROTECT_CITY_STATE_1',			'{2_MajorCivName:textkey} gave {1_MinorCivName:textkey} the gift of protection. Attacking the City-State will greatly damage relations and may lead to war.'),
			('TXT_KEY_LEADER_CLSEATTLE_DECLARATION_ABANDON_CITY_STATE_1',			'{2_MajorCivName:textkey} has taken back its guarantee of protecting {1_MinorCivName:textkey}.'),
			('TXT_KEY_LEADER_CLSEATTLE_ATTACKED_PROTECTED_CITY_STATE_1',			'At our last potlatch, we gave {@1_MinorCivName} the gift of protection. It seems that you do not value that gift.'),
			('TXT_KEY_LEADER_CLSEATTLE_BULLIED_PROTECTED_CITY_STATE_1',				'At our last potlatch, we gave {@1_MinorCivName} the gift of protection. It seems that you do not value that gift.'),
			('TXT_KEY_LEADER_CLSEATTLE_DONT_SETTLE_NO_1',							'I cannot accept. You have an abundance of land here, and we shall enjoy it together.'),
			('TXT_KEY_LEADER_CLSEATTLE_DONT_SETTLE_YES_1',							'Alright, we will give the gift of not settling near your lands.'),
			('TXT_KEY_LEADER_CLSEATTLE_LUXURY_TRADE_1',								'This is a fine gift, very generous.'),
			('TXT_KEY_LEADER_CLSEATTLE_OPEN_BORDERS_EXCHANGE_1',					'Let us gift eachother with free passage into our lands.'),
			('TXT_KEY_LEADER_CLSEATTLE_RESPONSE_REQUEST_1',							'I believe this is the source of your greatness. Please share it with us.'),
			('TXT_KEY_LEADER_CLSEATTLE_ATTACKED_HOSTILE_1',							'An enemy is never far from stabbing you. A man who knows his enemy knows to watch for a blade. I saw this coming, but prayed that it would not, for your sake.'),
			('TXT_KEY_LEADER_CLSEATTLE_ATTACKED_EXCITED_1',							'The spirit of God will punish you for this, and I will watch!'),
			('TXT_KEY_LEADER_CLSEATTLE_ATTACKED_SAD_1',								'The spirit of God will punish you for this.'),
			('TXT_KEY_LEADER_CLSEATTLE_ATTACKED_BETRAYED_1',						'An enemy is never far from stabbing you. A man who knows his enemy knows to watch for a blade.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_GENERIC_1',								'The Coast Salish nobility require slaves from the nations around us. It''s all part of what makes them nobles. Don''t worry. We treat our slaves well.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_GENERIC_2',								'Greetings! I hate to inform you that we are raiding you, but, you see, it''s all part of the glorious season that we find ourselves in. I''d call off my raiders, but they''ve already left.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_LAND_1',									'I warned you about taking the land given us by the Creator. We will have to take it back.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_WORLD_CONQUEST_1',						'It is a pity and a strange thing, I think, that the Creator smiles on us while he rejects you. So be it, we will soon possess all of the world.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_OPPORTUNITY_1',							'Circumstances have given me a gift I cannot refuse. A gift of gold, of lands, of resources, and slaves. Don''t worry. We treat our slaves well.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_DESPERATE_1',							'I cannot hope to match your greatness unless I bring you down to a more attainable level. This was necessary.'),
			('TXT_KEY_LEADER_CLSEATTLE_DOW_BETRAYAL_1',								'Backstabbing? Oh, no! I am merely accepting the gift of your complacency.'),
			('TXT_KEY_LEADER_CLSEATTLE_TOO_SOON_NO_PEACE_1',						'Peace is not a gift that a man of war can give to the people he is attacking.'),
			('TXT_KEY_LEADER_CLSEATTLE_BAD_1',										'I cannot accept.'),
			('TXT_KEY_LEADER_CLSEATTLE_GOOD_1',										'This is a generous offer.');