--==========================================================================================================================
-- PROMOTIONS
--==========================================================================================================================	
-- UnitPromotions
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, DisabledHelp, Button, PortraitIndex, IconAtlas, HotKey, HotKeyAlt, HotKeyPriority, HotKeyPriorityAlt, OrderPriority, AltDown, AltDownAlt, ShiftDown, ShiftDownAlt, CtrlDown, CtrlDownAlt, Sound, CannotBeChosen, LostWithUpgrade, NotWithUpgrade, InstaHeal, Leader, Blitz, Amphib, River, EnemyRoute, RivalTerritory, MustSetUpToRangedAttack, RangedSupportFire, CanMoveAfterAttacking, AlwaysHeal, HealOutsideFriendly, HillsDoubleMove, RoughTerrainEndsTurn, IgnoreTerrainCost, HoveringUnit, FlatMovementCost, CanMoveImpassable, NoCapture, OnlyDefensive, NoDefensiveBonus, NukeImmune, HiddenNationality, AlwaysHostile, NoRevealMap, Recon, CanMoveAllTerrain, FreePillageMoves, AirSweepCapable, AllowsEmbarkation, EmbarkedAllWater, HealIfDestroyExcludesBarbarians, RangeAttackIgnoreLOS, CityAttackOnly, CaptureDefeatedEnemy, HealOnPillage, IgnoreGreatGeneralBenefit, IgnoreZOC, HasPostCombatPromotions, PostCombatPromotionsExclusive, RangedAttackModifier, InterceptionCombatModifier, InterceptionDefenseDamageModifier, AirSweepCombatModifier, ExtraAttacks, ExtraNavalMovement, VisibilityChange, MovesChange, MoveDiscountChange, RangeChange, InterceptChanceChange, NumInterceptionChange, EvasionChange, CargoChange, EnemyHealChange, NeutralHealChange, FriendlyHealChange, SameTileHealChange, AdjacentTileHealChange, EnemyDamageChance, NeutralDamageChance, EnemyDamage, NeutralDamage, CombatPercent, CityAttack, CityDefense, RangedDefenseMod, HillsAttack, HillsDefense, OpenAttack, OpenRangedAttackMod, OpenDefense, RoughAttack, RoughRangedAttackMod, RoughDefense, AttackFortifiedMod, AttackWoundedMod, FlankAttackModifier, NearbyEnemyCombatMod, NearbyEnemyCombatRange, UpgradeDiscount, ExperiencePercent, AdjacentMod, AttackMod, DefenseMod, DropRange, GreatGeneral, GreatAdmiral, GreatGeneralModifier, GreatGeneralReceivesMovement, GreatGeneralCombatModifier, FriendlyLandsModifier, FriendlyLandsAttackModifier, OutsideFriendlyLandsModifier, HPHealedIfDestroyEnemy, ExtraWithdrawal, EmbarkExtraVisibility, EmbarkDefenseModifier, CapitalDefenseModifier, CapitalDefenseFalloff, CityAttackPlunderModifier, ReligiousStrengthLossRivalTerritory, TradeMissionInfluenceModifier, TradeMissionGoldModifier, GoldenAgeValueFromKills, Sapper, HeavyCharge, LayerAnimationPath, TechPrereq, Invisible, SeeInvisible, PromotionPrereq, PromotionPrereqOr1, PromotionPrereqOr2, PromotionPrereqOr3, PromotionPrereqOr4, PromotionPrereqOr5, PromotionPrereqOr6, PromotionPrereqOr7, PromotionPrereqOr8, PromotionPrereqOr9, PediaType, PediaEntry)
SELECT Type || '_NATIONALISM', Description, Help, DisabledHelp, Button, PortraitIndex, IconAtlas, HotKey, HotKeyAlt, HotKeyPriority, HotKeyPriorityAlt, OrderPriority, AltDown, AltDownAlt, ShiftDown, ShiftDownAlt, CtrlDown, CtrlDownAlt, Sound, CannotBeChosen, LostWithUpgrade, NotWithUpgrade, InstaHeal, Leader, Blitz, Amphib, River, EnemyRoute, RivalTerritory, MustSetUpToRangedAttack, RangedSupportFire, CanMoveAfterAttacking, AlwaysHeal, HealOutsideFriendly, HillsDoubleMove, RoughTerrainEndsTurn, IgnoreTerrainCost, HoveringUnit, FlatMovementCost, CanMoveImpassable, NoCapture, OnlyDefensive, NoDefensiveBonus, NukeImmune, HiddenNationality, AlwaysHostile, NoRevealMap, Recon, CanMoveAllTerrain, FreePillageMoves, AirSweepCapable, AllowsEmbarkation, EmbarkedAllWater, HealIfDestroyExcludesBarbarians, RangeAttackIgnoreLOS, CityAttackOnly, CaptureDefeatedEnemy, HealOnPillage, IgnoreGreatGeneralBenefit, IgnoreZOC, HasPostCombatPromotions, PostCombatPromotionsExclusive, RangedAttackModifier, InterceptionCombatModifier, InterceptionDefenseDamageModifier, AirSweepCombatModifier, ExtraAttacks, ExtraNavalMovement, VisibilityChange, MovesChange, MoveDiscountChange, RangeChange, InterceptChanceChange, NumInterceptionChange, EvasionChange, CargoChange, EnemyHealChange, NeutralHealChange, FriendlyHealChange, SameTileHealChange, AdjacentTileHealChange, EnemyDamageChance, NeutralDamageChance, EnemyDamage, NeutralDamage, CombatPercent, CityAttack, CityDefense, RangedDefenseMod, HillsAttack, HillsDefense, OpenAttack, OpenRangedAttackMod, OpenDefense, RoughAttack, RoughRangedAttackMod, RoughDefense, AttackFortifiedMod, AttackWoundedMod, FlankAttackModifier, NearbyEnemyCombatMod, NearbyEnemyCombatRange, UpgradeDiscount, ExperiencePercent, AdjacentMod, AttackMod, DefenseMod, DropRange, GreatGeneral, GreatAdmiral, GreatGeneralModifier, GreatGeneralReceivesMovement, GreatGeneralCombatModifier, FriendlyLandsModifier, FriendlyLandsAttackModifier, OutsideFriendlyLandsModifier, HPHealedIfDestroyEnemy, ExtraWithdrawal, EmbarkExtraVisibility, EmbarkDefenseModifier, CapitalDefenseModifier, CapitalDefenseFalloff, CityAttackPlunderModifier, ReligiousStrengthLossRivalTerritory, TradeMissionInfluenceModifier, TradeMissionGoldModifier, GoldenAgeValueFromKills, Sapper, HeavyCharge, LayerAnimationPath, TechPrereq, Invisible, SeeInvisible, PromotionPrereq, PromotionPrereqOr1, PromotionPrereqOr2, PromotionPrereqOr3, PromotionPrereqOr4, PromotionPrereqOr5, PromotionPrereqOr6, PromotionPrereqOr7, PromotionPrereqOr8, PromotionPrereqOr9, PediaType, PediaEntry
FROM UnitPromotions WHERE Type IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR Type IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, DoubleMove, Impassable, PassableTech, PediaType)
SELECT PromotionType || '_NATIONALISM', TerrainType, Attack, Defense, DoubleMove, Impassable, PassableTech, PediaType
FROM UnitPromotions_Terrains WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_Features (PromotionType, FeatureType, Attack, Defense, DoubleMove, Impassable, PassableTech, PediaType)
SELECT PromotionType || '_NATIONALISM', FeatureType, Attack, Defense, DoubleMove, Impassable, PassableTech, PediaType
FROM UnitPromotions_Features WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_UnitClasses (PromotionType, UnitClassType, Modifier, Attack, Defense, PediaType)
SELECT PromotionType || '_NATIONALISM', UnitClassType, Modifier, Attack, Defense, PediaType
FROM UnitPromotions_UnitClasses WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_Domains (PromotionType, DomainType, Modifier)
SELECT PromotionType || '_NATIONALISM', DomainType, Modifier
FROM UnitPromotions_Domains WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_UnitCombatMods (PromotionType, UnitCombatType, Modifier)
SELECT PromotionType || '_NATIONALISM', UnitCombatType, Modifier
FROM UnitPromotions_UnitCombatMods WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT PromotionType || '_NATIONALISM', UnitCombatType
FROM UnitPromotions_UnitCombats WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_CivilianUnitType (PromotionType, UnitType)
SELECT PromotionType || '_NATIONALISM', UnitType
FROM UnitPromotions_CivilianUnitType WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO UnitPromotions_PostCombatRandomPromotion (PromotionType, NewPromotion)
SELECT PromotionType || '_NATIONALISM', NewPromotion
FROM UnitPromotions_PostCombatRandomPromotion WHERE PromotionType IN (SELECT PromotionType FROM Policy_FreePromotions WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0)) OR PromotionType IN (SELECT PromotionType FROM Policy_FreePromotionUnitCombats WHERE PolicyType IN (SELECT Type FROM Policies WHERE PolicyBranchType IS NOT NULL AND Level = 0));
--==========================================================================================================================
--==========================================================================================================================