CREATE TABLE IF NOT EXISTS CustomModOptions (Name text, Value integer, class integer, DbUpdates integer);

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_PLOT' AND Value = 0;

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT' AND Value = 0;

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT_ENDED' AND Value = 0;

CREATE TABLE IF NOT EXISTS UnitPromotions_YieldFromKills (PromotionType text, YieldType text, Yield integer);
--FOR THE QUEEN, DO NOT MODIFY THIS THING ABOVE--
 
INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION_GG', 'TXT_KEY_PROMOTION_REEDUCATION_GG', 'TXT_KEY_PROMOTION_REEDUCATION_GG_HELP', 'AS2D_IF_LEVELUP', 3, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION_GG2', 'TXT_KEY_PROMOTION_REEDUCATION_GG2', 'TXT_KEY_PROMOTION_REEDUCATION_GG2_HELP', 'AS2D_IF_LEVELUP', 4, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION_GG2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION_GG3', 'TXT_KEY_PROMOTION_REEDUCATION_GG3', 'TXT_KEY_PROMOTION_REEDUCATION_GG3_HELP', 'AS2D_IF_LEVELUP', 5, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION_GG3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION', 'TXT_KEY_PROMOTION_REEDUCATION', 'TXT_KEY_PROMOTION_REEDUCATION_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION2', 'TXT_KEY_PROMOTION_REEDUCATION2', 'TXT_KEY_PROMOTION_REEDUCATION2_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_REEDUCATION3', 'TXT_KEY_PROMOTION_REEDUCATION3', 'TXT_KEY_PROMOTION_REEDUCATION3_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_REEDUCATION3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_REEDUCATION', 'YIELD_CULTURE', 50
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_REEDUCATION2', 'YIELD_CULTURE', 75
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_REEDUCATION3', 'YIELD_CULTURE', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS_GG', 'TXT_KEY_PROMOTION_PIOUS_GG', 'TXT_KEY_PROMOTION_PIOUS_GG_HELP', 'AS2D_IF_LEVELUP', 3, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS_GG2', 'TXT_KEY_PROMOTION_PIOUS_GG2', 'TXT_KEY_PROMOTION_PIOUS_GG2_HELP', 'AS2D_IF_LEVELUP', 4, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS_GG2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS_GG3', 'TXT_KEY_PROMOTION_PIOUS_GG3', 'TXT_KEY_PROMOTION_PIOUS_GG3_HELP', 'AS2D_IF_LEVELUP', 5, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS_GG3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS', 'TXT_KEY_PROMOTION_PIOUS', 'TXT_KEY_PROMOTION_PIOUS_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS2', 'TXT_KEY_PROMOTION_PIOUS2', 'TXT_KEY_PROMOTION_PIOUS2_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_PIOUS3', 'TXT_KEY_PROMOTION_PIOUS3', 'TXT_KEY_PROMOTION_PIOUS3_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_PIOUS3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_PIOUS', 'YIELD_FAITH', 75
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_PIOUS2', 'YIELD_FAITH', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_PIOUS3', 'YIELD_FAITH', 125
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER_GG', 'TXT_KEY_PROMOTION_SCAVENGER_GG', 'TXT_KEY_PROMOTION_SCAVENGER_GG_HELP', 'AS2D_IF_LEVELUP', 3, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER_GG2', 'TXT_KEY_PROMOTION_SCAVENGER_GG2', 'TXT_KEY_PROMOTION_SCAVENGER_GG2_HELP', 'AS2D_IF_LEVELUP', 4, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER_GG2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER_GG3', 'TXT_KEY_PROMOTION_SCAVENGER_GG3', 'TXT_KEY_PROMOTION_SCAVENGER_GG3_HELP', 'AS2D_IF_LEVELUP', 5, 'GG_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER_GG3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER', 'TXT_KEY_PROMOTION_SCAVENGER', 'TXT_KEY_PROMOTION_SCAVENGER_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER2', 'TXT_KEY_PROMOTION_SCAVENGER2', 'TXT_KEY_PROMOTION_SCAVENGER2_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER2', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, ExperiencePercent, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_SCAVENGER3', 'TXT_KEY_PROMOTION_SCAVENGER3', 'TXT_KEY_PROMOTION_SCAVENGER3_HELP', 'AS2D_IF_LEVELUP', 25, 6, 'PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_SCAVENGER3', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_SCAVENGER', 'YIELD_GOLD', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_SCAVENGER2', 'YIELD_GOLD', 125
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_SCAVENGER3', 'YIELD_GOLD', 150
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_MUHFREEDOM_GG', 'TXT_KEY_PROMOTION_MUHFREEDOM_GG', 'TXT_KEY_PROMOTION_MUHFREEDOM_GG_HELP', 'AS2D_IF_LEVELUP', 10, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHFREEDOM_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_MUHORDER_GG', 'TXT_KEY_PROMOTION_MUHORDER_GG', 'TXT_KEY_PROMOTION_MUHORDER_GG_HELP', 'AS2D_IF_LEVELUP', 10, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHORDER_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry, CannotBeChosen)
SELECT 'PROMOTION_MUHAUTOCRACY_GG', 'TXT_KEY_PROMOTION_MUHAUTOCRACY_GG', 'TXT_KEY_PROMOTION_MUHAUTOCRACY_GG_HELP', 'AS2D_IF_LEVELUP', 10, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHAUTOCRACY_GG', 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, DefenseMod, PortraitIndex, IconAtlas, PediaType, PediaEntry, MovesChange, OutsideFriendlyLandsModifier, FriendlyLandsModifier, CannotBeChosen)
SELECT 'PROMOTION_MUHFREEDOM', 'TXT_KEY_PROMOTION_MUHFREEDOM', 'TXT_KEY_PROMOTION_MUHFREEDOM_HELP', 'AS2D_IF_LEVELUP', 10, 2, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHFREEDOM', 1, 15, 15, 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, SameTileHealChange, PortraitIndex, IconAtlas, PediaType, PediaEntry, MovesChange, OutsideFriendlyLandsModifier, FriendlyLandsModifier, CannotBeChosen)
SELECT 'PROMOTION_MUHORDER', 'TXT_KEY_PROMOTION_MUHORDER', 'TXT_KEY_PROMOTION_MUHORDER_HELP', 'AS2D_IF_LEVELUP', 5, 2, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHORDER', 1, 10, 20, 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions (Type, Description, Help, Sound, AttackWoundedMod, PortraitIndex, IconAtlas, PediaType, PediaEntry, MovesChange, OutsideFriendlyLandsModifier, FriendlyLandsModifier, CannotBeChosen)
SELECT 'PROMOTION_MUHAUTOCRACY', 'TXT_KEY_PROMOTION_MUHAUTOCRACY', 'TXT_KEY_PROMOTION_MUHAUTOCRACY_HELP', 'AS2D_IF_LEVELUP', 25, 2, 'EXPANSION2_PROMOTION_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_MUHAUTOCRACY', 1, 20, 10, 1
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_MUHFREEDOM', 'YIELD_CULTURE', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_MUHORDER', 'YIELD_CULTURE', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_MUHAUTOCRACY', 'YIELD_CULTURE', 100
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='EVENTS_PLOT' AND Value= 1 );